trigger:
  branches:
    include:
      - adf_publish  # Use the branch containing the ARM templates

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy Azure Data Factory ARM Templates'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '<ServiceConnectionName>'  # Replace with your Azure service connection name
    subscriptionId: '<SubscriptionID>'  # Replace with your Azure subscription ID
    action: 'Create Or Update Resource Group'
    resourceGroupName: '<ResourceGroupName>'  # Replace with your Azure resource group
    location: '<Region>'  # Replace with your ADF location
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/arm_template/arm_template.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/arm_template/arm_template_parameters.json'
    overrideParameters: '-factoryName "<ADFName>"'  # Replace with your ADF name
